require_remote "lib/manager/general_manager.rb"
require_remote "lib/manager/input_manager.rb"
require_remote "lib/manager/output_manager.rb"
require_remote "lib/manager/dungeon_manager.rb"
require_remote "lib/manager/event_manager.rb"
require_remote "lib/manager/message_manager.rb"
require_remote "lib/manager/level_manager.rb"
